steps:
    - name: Get data
      run: dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    # Step 1: Build the Docker image
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-f",
              "./dockerfiles/trainer.dockerfile",
              "-t",
              "gcr.io/dtumlops-410721/trainer:latest",
              ".",
          ]

    # Step 2: Push the Docker image to Artifact Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/dtumlops-410721/trainer:latest"]

images:
    - "gcr.io/dtumlops-410721/trainer:latest"